use codeup_tests_db;

INSERT INTO albums (artist, name, date, sales, genre)
VALUES ('Michael Jackson',	'Thriller',	'1982', '66',	'Pop, post-disco, funk, rock'),
       ('AC/DC',	'Back in Black',	'1980', '50',	'Hard rock'),
       ('Meat Loaf',	'Bat Out of Hell',	'1977',	'50', 'Hard rock, glam rock, progressive rock'),
       ('Pink Floyd',	'The Dark Side of the Moon',	'1973',	'45', 'Progressive rock'),
       ('Whitney Houston',	'The Bodyguard',	'1992', '45', 'R&B, soul, pop, soundtrack'),
       ('Eagles',	'Their Greatest Hits (1971–1975)',	'1976',	'42', 'Country rock, soft rock, folk rock'),
       ('Bee Gees',	'Saturday Night Fever',	'1977',	'40', 'Disco'),
       ('Fleetwood Mac',	'Rumours',	'1977',	'40', 'Soft rock'),
       ('Shania Twain',	'Come On Over',	'1997', '40',	'Country, pop'),
       ('Led Zeppelin',	'Led Zeppelin IV',	'1971', '38',	'Hard rock, heavy metal, folk rock'),
       ('Michael Jackson',	'Bad',	'1987', '37', 'Pop, rhythm and blues, funk and rock'),
       ('Alanis Morissette',	'Jagged Little Pill',	'1995', '35',	'Alternative rock'),
       ('Michael Jackson',	'Dangerous',	'1991', '33',	'New jack swing, R&B and pop'),
       ('Celine Dion',	'Falling into You',	'1996',	'32', 'Pop, soft rock'),
       ('Eagles',	'Hotel California',	'1976', '32',	'Soft rock'),
       ('The Beatles',	'Sgt. Pepper''s Lonely Hearts Club Band',	'1967', '32', 'Rock'),
       ('Various artists',	'Dirty Dancing',	'1987', '32',	'Pop, rock, R&B'),
       ('Adele','21',	'2011', '31',	'Pop, soul'),
       ('Madonna',	'The Immaculate Collection',	'1990', '31',	'Pop, dance'),
       ('Celine Dion',	'Let''s Talk About Love',	'1997', '31',	'Pop, soft rock'),
       ('Metallica',	'Metallica',	'1991', '31',	'Heavy metal'),
       ('The Beatles',	'1',	'2000', '31',	'Rock'),
       ('ABBA',	'Gold: Greatest Hits',	'1992', '30', 'Pop, disco'),
       ('The Beatles',	'Abbey Road',	'1969', '30',	'Rock'),
       ('Bruce Springsteen', 'Born in the U.S.A.',	'1984', '30',	'Heartland rock'),
       ('Dire Straits',	'Brothers in Arms',	'1985', '30',	'Roots rock, blues rock, soft rock'),
       ('James Horner',	'Titanic: Music from the Motion Picture',	'1997', '30',	'Film score'),
       ('Nirvana',	'Nevermind',	'1991',	'30', 'Grunge, alternative rock'),
       ('Pink Floyd',	'The Wall',	'1979', '30',	'Progressive rock'),
       ('Santana',	'Supernatural',	'1999',	'30', 'Latin rock'),
       ('Guns N'' Roses',	'Appetite for Destruction',	'1987', '30',	'Hard rock'),
       ('Elton John',	'Goodbye Yellow Brick Road',	'1973', '30',	'rock, pop rock glam rock');
